// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/K-Kizuku/techer-me-backend/internal/app/handler"
	exchange3 "github.com/K-Kizuku/techer-me-backend/internal/app/handler/exchange"
	user3 "github.com/K-Kizuku/techer-me-backend/internal/app/handler/user"
	"github.com/K-Kizuku/techer-me-backend/internal/app/repository/exchange"
	"github.com/K-Kizuku/techer-me-backend/internal/app/repository/user"
	exchange2 "github.com/K-Kizuku/techer-me-backend/internal/app/service/exchange"
	user2 "github.com/K-Kizuku/techer-me-backend/internal/app/service/user"
	"github.com/K-Kizuku/techer-me-backend/pkg/db"
)

// Injectors from wire.go:

func InitHandler() *handler.Root {
	sqlxDB := db.New()
	iRepository := user.New(sqlxDB)
	iUserService := user2.New(iRepository)
	userHandler := user3.New(iUserService)
	exchangeIRepository := exchange.New(sqlxDB)
	iExchangeService := exchange2.New(exchangeIRepository)
	exchangeHandler := exchange3.New(iExchangeService)
	root := handler.New(userHandler, exchangeHandler)
	return root
}
