// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/K-Kizuku/techer-me-backend/internal/app/handler"
	event3 "github.com/K-Kizuku/techer-me-backend/internal/app/handler/event"
	exchange3 "github.com/K-Kizuku/techer-me-backend/internal/app/handler/exchange"
	image3 "github.com/K-Kizuku/techer-me-backend/internal/app/handler/image"
	user3 "github.com/K-Kizuku/techer-me-backend/internal/app/handler/user"
	"github.com/K-Kizuku/techer-me-backend/internal/app/repository/event"
	"github.com/K-Kizuku/techer-me-backend/internal/app/repository/exchange"
	"github.com/K-Kizuku/techer-me-backend/internal/app/repository/image"
	"github.com/K-Kizuku/techer-me-backend/internal/app/repository/user"
	event2 "github.com/K-Kizuku/techer-me-backend/internal/app/service/event"
	exchange2 "github.com/K-Kizuku/techer-me-backend/internal/app/service/exchange"
	image2 "github.com/K-Kizuku/techer-me-backend/internal/app/service/image"
	user2 "github.com/K-Kizuku/techer-me-backend/internal/app/service/user"
	"github.com/K-Kizuku/techer-me-backend/pkg/db"
)

// Injectors from wire.go:

func InitHandler() *handler.Root {
	sqlxDB := db.New()
	iRepository := user.New(sqlxDB)
	iUserService := user2.New(iRepository)
	userHandler := user3.New(iUserService)
	exchangeIRepository := exchange.New(sqlxDB)
	iExchangeService := exchange2.New(exchangeIRepository)
	exchangeHandler := exchange3.New(iExchangeService)
	eventIRepository := event.New(sqlxDB)
	iEventService := event2.New(eventIRepository)
	eventHandler := event3.New(iEventService)
	imageIRepository := image.New(sqlxDB)
	iImageService := image2.New(imageIRepository)
	imageHandler := image3.New(iImageService)
	root := handler.New(userHandler, exchangeHandler, eventHandler, imageHandler)
	return root
}
